### ISSUE TITLE
Question: compare diseased vs control fluxomes

### ISSUE THREAD

**Issue by johaGL** [fumiomatsuda/mfapy#5]
Dear mfapy team: Thank you for your great software. I would like to know if you included any functionality to compare between diseased vs control 13C-MFA results. thank you in advance.

**Comment by fumiomatsuda** [comment]
Thanks for your comment, and I'm sorry for my slow response. Unfortunately, the current version of mfapy does not have functions for such statistical analysis.

**Comment by johaGL** [comment]
Thank you very much @fumiomatsuda , your answer is welcome, my question was not subjected to time limits.  :)   Kind regards
